### ISSUE TITLE
Nginx does not recognize Brotli

### ISSUE THREAD

**Issue by chiqui3d** [fholzer/docker-nginx-brotli#13]
Hi,

I'm using your image for docker composer, but in my nginx.conf I have to comment "brotli on", so that I can up the nginx service, if nginx doesn't work.

This is my Dockerfile:

```
FROM fholzer/nginx-brotli:v1.14.0

RUN apk add --update nginx
RUN rm -rf /var/cache/apk/* && rm -rf /tmp/*

ADD nginx.conf /etc/nginx/
ADD symfony.conf /etc/nginx/conf.d/
ADD gzip.conf /etc/nginx/conf.d/
#ADD brotli.conf /etc/nginx/conf.d/

RUN adduser -D -g '' -G www-data www-data

CMD ["nginx"]

EXPOSE 80
EXPOSE 443
```
nginx.conf

```
user www-data;
worker_processes 4;
pid /run/nginx.pid;

events {
  worker_connections  2048;
  multi_accept on;
  use epoll;
}

http {
  server_tokens off;
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 15;
  types_hash_max_size 2048;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log off;
  #error_log off;
  open_file_cache max=100;
  #brotli on;
  gzip on;
  gzip_disable "msie6";
  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/sites-enabled/*;
}

daemon off;
```

**Comment by fholzer** [comment]
Hi,

could you please try again, but remove the line `RUN apk add --update nginx`. This image contains nginx and the brotli module. Also, my image already contains a user and group used by nginx. Both are simply called "nginx", so please also remove the line to create a new user and group from your Dockerfile. As a result please also change the `user` directive in you nginx config to `user nginx;`.

Cheers,
Ferdinand

**Comment by fholzer** [comment]
You can also remove the `EXPOSE` and `CMD` directives from your Dockerfile, as they will be inherited from my image.

**Comment by chiqui3d** [comment]
Thank you very much. Works perfectly.
Could you also add "cerbot" to generate ssl certificates for a domain?
