### ISSUE TITLE
Alpine 3.8 support?

### ISSUE THREAD

**Issue by onpaws** [fholzer/docker-nginx-brotli#14]
Hi, 
Thanks for making this handy package. I appreciate the minimal touch.

I see the Nginx maintainers have [released 1.15.4](https://github.com/nginxinc/docker-nginx/commit/3c446adddf7b04e877d5c5191b151c794c74bb58) recently.
Was wondering if there was a plan to update this repo?

**Comment by onpaws** [comment]
Ah, I think I've just realized we deliberately targeting `stable` release channel only in this repo.

I see Alpine also got [bumped to version 3.8](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile) - seems like it'd be nice to update our Dockerfile to reflect the changes (I understand there are security-related changes since 3.6 was released)

**Comment by onpaws** [comment]
Danke gentlemen, appreciate the good work!

**Comment by fholzer** [comment]
1.15.8 released
