### ISSUE TITLE
Split perl and non-perl images?

### ISSUE THREAD

**Issue by btmorex** [fholzer/docker-nginx-brotli#28]
It would be nice to do the same thing that the official nginx images do and split out perl builds. Perl alone more than doubles the size of the image.

**Comment by onpaws** [comment]
This appears to be the relevant commit that introduced the Perl module.
https://github.com/nginxinc/docker-nginx/commit/89f799750f5967a1b2ed16081457c04ca52307ea

Curious, do you happen to know why Perl was introduced upstream? Maybe the nginx Docker maintainers are targeting specific customer(s) that use Perl?
Not having used Perl on the web since the Movable Type days it seems a bit unusual to ship it in the 'generic' nginx image. But perhaps there's a good reason; would be interested to learn why.

**Comment by onpaws** [comment]
@fholzer Not sure if you needed Perl for your purposes -- what are your thoughts? I ask b/c both @btmorex and an nginx Docker maintainer, @thresheek seem to avoid it:
 > the default "latest" or similar images do not have it.

https://github.com/nginxinc/docker-nginx/commit/89f799750f5967a1b2ed16081457c04ca52307ea

Would you be open to a PR? What's your take on it?

**Comment by fholzer** [comment]
good point, will try to look into this in the next couple days

**Comment by fholzer** [comment]
As perl is rarely used I'm more than OK with removing it from my image, though I won't be maintaining a separate image for it. I hope no one counts on it being supported.

Latest table stable and mainline version images are updated and no longer include perl:
* latest (master/stable)
* v1.18.0
* mainline
* v1.19.1 (still building)

**Comment by onpaws** [comment]
Thanks @fholzer! 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/182515/88456672-bcaf6080-ce7f-11ea-984b-b5da9841bdbb.png">
50% image size reduction seems nice.

Wanted to share a completely unscientific data point  of the runtime memory difference as reported by `docker stats`.
I'm running just a SPA app -- local dev only, nothing production. So just a small/trivial data point, with that said, I was curious to see MEM USAGE
1.16.1
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/182515/88456661-a5707300-ce7f-11ea-96d7-9e822628fbbe.png">

1.19.1
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/182515/88456769-c9808400-ce80-11ea-927a-d9c96bc30e31.png">

Could be completely unrelated to the Perl removal, not sure, but maybe it's possible there could be a small reduction in memory usage too. 

Either way, nice work and danke!
