### ISSUE TITLE
`envsubst` stopped working

### ISSUE THREAD

**Issue by sprymiker** [fholzer/docker-nginx-brotli#34]
Hello, we faced a critical issue using the recently updated image.

Running `envsubst` leads to the following errors

```
#18 0.322 Error loading shared library libintl.so.8: No such file or directory (needed by /usr/local/bin/envsubst)
--
884 | #18 0.322 Error relocating /usr/local/bin/envsubst: libintl_bindtextdomain: symbol not found
885 | #18 0.322 Error relocating /usr/local/bin/envsubst: libintl_gettext: symbol not found
886 | #18 0.322 Error relocating /usr/local/bin/envsubst: libintl_textdomain: symbol not found
```

**Comment by fl0ge** [comment]
Hello, we are facing the same issue since the updated image v1.18.0

**Comment by fholzer** [comment]
this affects:
* latest (master)
* v1.18.0
* mainline
* v1.19.1

Should be fixed by latest commit in each branch. (e4ecd2ed0ebd2ab2e1e137b419f9efabc3b07312 for on master) Will keep this open until all builds succeeded.

**Comment by fl0ge** [comment]
Thanks @fholzer 
I'll check with updated v1.18.0 tag when it will be available on docker hub.

**Comment by fl0ge** [comment]
I've tested the updated v1.18.0 tag and it's OK now.
I've seen updates for v1.19.1 and mainline at docker hub but not for now for latest: I can't tell if those 3 are OK but v1.18.0 works fine.
Thanks @fholzer for the quick fix

**Comment by fholzer** [comment]
Yeah, build for latest is still running. Not sure why it's so slow.
Will close this.

Cheers

**Comment by fholzer** [comment]
latest build finally succeeded.
