### ISSUE TITLE
`STOPSIGNAL SIGTERM` directive does not correspond with nginx control signals

### ISSUE THREAD

**Issue by rahil-p** [fholzer/docker-nginx-brotli#41]
Although `SIGTERM` generally allows for graceful shutdown, nginx responds to POSIX signals unconventionally ([docs](https://nginx.org/en/docs/control.html)):

> TERM, INT fast shutdown
> QUIT graceful shutdown

Since https://github.com/nginxinc/docker-nginx/commit/3fb70ddd7094c1fdd50cc83d432643dc10ab6243, the official image uses `STOPSIGNAL SIGQUIT`.

Related issue: nginxinc/docker-nginx#377

**Comment by fholzer** [comment]
fixed on master (stable) and mainline branches. latest (stable) tag is updated on docker hub already, mainline and version tagged images are still building, should be published about an hour from now, or two.
