### ISSUE TITLE
Tag latest with a specific verison

### ISSUE THREAD

**Issue by GeyseR** [fholzer/docker-nginx-brotli#50]
Hi!

After recent updates to the image's entrypoint/run commands https://github.com/fholzer/docker-nginx-brotli/commit/2a6e0ebd0596a4ed75c67ed06bbed711468aa6fc#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R164-R165, our installation of the image became broken.

One of the reasons was that we weren't able to pin the version of the image that we use to a specific version. The latest tag just doesn't have any specific tag to pin to. Would be great to have such a tag that we can pin to the latest version and don't be afraid that it will become broken again.

**Comment by fholzer** [comment]
Hi,

sorry to hear that. I've been working on getting the image updated and introducing use of Github Actions the past couple of days. Regarding tags, have you tried using a tag for a specific version? .e.g `fholzer/nginx-brotli:v1.18.0` or `fholzer/nginx-brotli:v1.19.1`? These are very unlikely to be updated with breaking changes, while the `latest` and `mainline-latest` tags are. Or maybe I misunderstood how the issue relates to your use of tags.

At the moment there's still new builds running for both `latest` and `mainline-latest`, once these finished, I'll add tags for these new versions `v1.20.2` and `v.1.21.6` 

Cheers,
Ferdinand

**Comment by GeyseR** [comment]
so, we should consider latest as "preview" release and when they become "stable" you will label them with a specific version, right?

**Comment by fholzer** [comment]
Well, no. `latest` simply points to the latest stable release of nginx. With each new version there could also be changes. I try to keep those to a minimum, though sometimes they could break things like in your case. What I was trying to say is that if you pin to a specific version tag, then you can expect there to be no such breaking changes. Though in that case you'll need to manually change the tag you use when a new version is released, but at least in that case it is less of a surprise that something could break when actively switching to a new version's tag. Does that make sense?

**Comment by GeyseR** [comment]
so, you are saying that we should choose between the latest nginx version (without pinning) or the previous version with the ability to pin to it? 🤔

**Comment by GeyseR** [comment]
the official nginx image is tagged with both "latest" and version tags:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/1364479/155230275-2998ea35-cb60-4b86-87c0-64bca0908e17.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1364479/155230389-d80f0037-408a-49fe-8bd6-7a61375e1fa6.png">

**Comment by fholzer** [comment]
Not quite. There'll also be tags for v1.20.2 (stable) and v1.21.6 (mainline) published shortly. I am just in the process of switching from TravisCI to Github Actions, and generally updating the Dockerfile. These version tags should be available about an hour from now.

**Comment by fholzer** [comment]
image tags v1.20.2 (stable) and v1.21.6 (mainline) are now published.

**Comment by GeyseR** [comment]
thanks for the explanation, we pinned our images to the desired versions 👍
