### ISSUE TITLE
Local docker command starts breaking

### ISSUE THREAD

**Issue by agarwalvinit** [fholzer/docker-nginx-brotli#53]
My last command at dockerfile is `CMD ["/bin/ash", "run.sh"]`
And I am getting an error - nginx: invalid option: "ash"

**Comment by agarwalvinit** [comment]
As we found out the entrypoint is added which is nginx, can this be reason behind this issue?

**Comment by fholzer** [comment]
yes that's likely because I added the entrypoint.
If you have a Dockerfile using FROM this image, you could try adding this to your Dockerfile:

```
ENTRYPOINT ["/bin/ash"]
CMD ["run.sh"]
```
